### ISSUE TITLE
Broken with 1.43

### ISSUE THREAD

**Issue by jdlrobson** [Halopedia/Onyx#8]
When viewing the Onxy skin in 1.43 I get fatal errors.
Is this skin still being maintained?

https://www.mediawiki.org/wiki/Skin:Onyx has been marked as "unstable" status

**Comment by mary-kate** [comment]
@jdlrobson Surely _you_ know better than to post an "omg it's broken!!11" report without any meaningful backtrace or other information...

But to answer your question: to my knowledge, yes. I can't speak for Daniel, but I've tested this skin on 1.39 and it works fine for me locally. As 1.39 is still the latest LTS release (per [mw:Version lifecycle](https://www.mediawiki.org/wiki/Version_lifecycle)), I've not tested any of the more recent versions as it's just not feasible to support random MW versions which are out of support all too soon. (At least this is the case for me as I support [more than one or two skins and/or extensions](https://www.mediawiki.org/wiki/User:Jack_Phoenix/extensions).)

Please come back with some meaningful debugging info and we can look into this issue and see what it takes to address this. Thanks!

**Comment by jdlrobson** [comment]
There are  issues relating to using no longer supported code. The immediate one (but possibly not the only one) being:
```
Deprecated: Use of wfGetDB was deprecated in MediaWiki 1.39. [Called from Onyx\ExtraSkinData::getRecentChanges in /Users/jdlrobson/git/core/skins/Onyx/includes/ExtraSkinData.php at line 70] in /Users/jdlrobson/git/core/includes/debug/MWDebug.php on line 385
MediaWiki internal error.

Original exception: [719b95a5b44befd14daa8e9f] /w/index.php/Paris?useskin=onyx Error: Class "Hooks" not found
Backtrace:
from /Users/jdlrobson/git/core/skins/Onyx/includes/OnyxTemplate.php(1555)
#0 /Users/jdlrobson/git/core/skins/Onyx/includes/OnyxTemplate.php(77): OnyxTemplate->buildToolbox(string, Onyx\Config)
#1 /Users/jdlrobson/git/core/includes/skins/SkinTemplate.php(164): OnyxTemplate->execute()
#2 /Users/jdlrobson/git/core/includes/skins/SkinTemplate.php(190): SkinTemplate->generateHTML()
#3 /Users/jdlrobson/git/core/includes/Output/OutputPage.php(3193): SkinTemplate->outputPage()
#4 /Users/jdlrobson/git/core/includes/actions/ActionEntryPoint.php(163): MediaWiki\Output\OutputPage->output(bool)
#5 /Users/jdlrobson/git/core/includes/MediaWikiEntryPoint.php(200): MediaWiki\Actions\ActionEntryPoint->execute()
#6 /Users/jdlrobson/git/core/index.php(58): MediaWiki\MediaWikiEntryPoint->run()
#7 {main}

Exception caught inside exception handler: [719b95a5b44befd14daa8e9f] /w/index.php/Paris?useskin=onyx Error: Class "Hooks" not found
Backtrace:
from /Users/jdlrobson/git/core/skins/Onyx/includes/OnyxTemplate.php(1555)
#0 /Users/jdlrobson/git/core/skins/Onyx/includes/OnyxTemplate.php(77): OnyxTemplate->buildToolbox(string, Onyx\Config)
#1 /Users/jdlrobson/git/core/includes/skins/SkinTemplate.php(164): OnyxTemplate->execute()
#2 /Users/jdlrobson/git/core/includes/skins/SkinTemplate.php(190): SkinTemplate->generateHTML()
#3 /Users/jdlrobson/git/core/includes/Output/OutputPage.php(3193): SkinTemplate->outputPage()
#4 /Users/jdlrobson/git/core/includes/exception/MWExceptionRenderer.php(190): MediaWiki\Output\OutputPage->output()
#5 /Users/jdlrobson/git/core/includes/exception/MWExceptionRenderer.php(109): MWExceptionRenderer::reportHTML(Error)
#6 /Users/jdlrobson/git/core/includes/exception/MWExceptionHandler.php(133): MWExceptionRenderer::output(Error, int)
#7 /Users/jdlrobson/git/core/includes/exception/MWExceptionHandler.php(237): MWExceptionHandler::report(Error)
#8 /Users/jdlrobson/git/core/includes/MediaWikiEntryPoint.php(222): MWExceptionHandler::handleException(Error, string)
#9 /Users/jdlrobson/git/core/includes/actions/ActionEntryPoint.php(82): MediaWiki\MediaWikiEntry
```
